name: Build and deploy JAR app to Azure Web App - students

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  # Job for running tests
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Set up Maven
        uses: actions/setup-java@v1
        with:
          maven-version: '3.8.4'  # You can specify your desired Maven version if necessary

      - name: Run tests
        run: |
          cd studentmanagementsystem
          mvn clean test -Dspring.profiles.active=test # Run tests with 'test' profile (application-test.properties)

  # Job for building the application
  build:
    runs-on: ubuntu-latest
    needs: test  # This makes sure the build only runs if tests pass

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Build with Maven
        run: |
          cd studentmanagementsystem
          mvn clean install
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/studentmanagementsystem/target/*.jar'

  # Job for deployment to Azure
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'students'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F2536DADFF644FE7A8B1EE21FBB633DE }}
          package: '*.jar'
